/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package automatastarter;

//imports
import utils.CardSwitcher;

public class OptionPanel extends javax.swing.JPanel {
    public static final String CARD_NAME = "option";
    CardSwitcher switcher = null;
    /**
      * Creates new form OptionPanel
      * @param p
    */
    public OptionPanel(CardSwitcher p) {
        initComponents();
        switcher = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reprodRateLabel = new javax.swing.JLabel();
        hungerLvlLabel = new javax.swing.JLabel();
        preyReprodLabel = new javax.swing.JLabel();
        preyReprodSlider = new javax.swing.JSlider();
        predReprodLabel = new javax.swing.JLabel();
        predReprodSlider = new javax.swing.JSlider();
        hungerLvlSlider = new javax.swing.JSlider();
        homeBtn = new javax.swing.JButton();
        gameBtn = new javax.swing.JButton();

        reprodRateLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        reprodRateLabel.setText("Reproduction Rate");

        hungerLvlLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        hungerLvlLabel.setText("Hunger Level Cap");

        preyReprodLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        preyReprodLabel.setText("Prey:");

        preyReprodSlider.setMinimum(1);
        preyReprodSlider.setValue(10);
        preyReprodSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                preyReprodSliderStateChanged(evt);
            }
        });

        predReprodLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        predReprodLabel.setText("Pred: ");

        predReprodSlider.setMinimum(1);
        predReprodSlider.setValue(5);
        predReprodSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                predReprodSliderStateChanged(evt);
            }
        });

        hungerLvlSlider.setMaximum(50);
        hungerLvlSlider.setMinimum(1);
        hungerLvlSlider.setValue(20);
        hungerLvlSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hungerLvlSliderStateChanged(evt);
            }
        });

        homeBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        homeBtn.setText("Back to Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        gameBtn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        gameBtn.setText("Back to Game");
        gameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reprodRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(preyReprodLabel)
                        .addGap(18, 18, 18)
                        .addComponent(preyReprodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(predReprodLabel)
                        .addGap(18, 18, 18)
                        .addComponent(predReprodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gameBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeBtn)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hungerLvlLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hungerLvlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(reprodRateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preyReprodLabel)
                    .addComponent(preyReprodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(predReprodLabel)
                    .addComponent(predReprodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(hungerLvlLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hungerLvlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn)
                    .addComponent(gameBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

//    on hunger level change
    private void hungerLvlSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hungerLvlSliderStateChanged
        int hungerLvl = hungerLvlSlider.getValue();
        GamePanel.p.setPredHungerVal(hungerLvl);
    }//GEN-LAST:event_hungerLvlSliderStateChanged

//    to intro panel
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        switcher.switchToCard(IntroPanel.CARD_NAME);
    }//GEN-LAST:event_homeBtnActionPerformed

//    to game
    private void gameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameBtnActionPerformed
        switcher.switchToCard(GamePanel.CARD_NAME);
    }//GEN-LAST:event_gameBtnActionPerformed

//    pred reproduction rate changes
    private void predReprodSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_predReprodSliderStateChanged
        int predRate = predReprodSlider.getValue();
        GamePanel.p.setPredReprodRate(predRate);
    }//GEN-LAST:event_predReprodSliderStateChanged

//    prey reproduction rate changes
    private void preyReprodSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_preyReprodSliderStateChanged
        int preyRate = preyReprodSlider.getValue();
        GamePanel.p.setPredReprodRate(preyRate);
    }//GEN-LAST:event_preyReprodSliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gameBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel hungerLvlLabel;
    private javax.swing.JSlider hungerLvlSlider;
    private javax.swing.JLabel predReprodLabel;
    private javax.swing.JSlider predReprodSlider;
    private javax.swing.JLabel preyReprodLabel;
    private javax.swing.JSlider preyReprodSlider;
    private javax.swing.JLabel reprodRateLabel;
    // End of variables declaration//GEN-END:variables
}
